[package]
name = "mailviewer-core"
version = "0.1.1"
edition = "2021"
authors = ["Alexandre Del Bigio"]
description = "Reading and sanitizing of eml and Outlook msg files, without a toolkit"
readme = "README.md"
repository = "https://github.com/alescdb/mailviewer-core"
license = "GPL-3.0+"

[dependencies]
ammonia = "4.1"
base64 = "0.23"
ctor = "1.0"
dtor = "1.0"
encoding_rs = "0.8"
futures-util = "0.3"
gio = "0.22"
glib = { version = "0.22", features = ["v2_66"] }
gmime = "0.8"
hex = "0.4"
lazy_static = "1.5"
log = "0.4"
msg_parser = "0.3"
uuid = { version = "1.26", features = ["v4"] }
